//! Python bindings for synthetic data generators

use dpb_synth::contact::ecg::{EcgMorphologyGenerator, EcgMorphologyParams};
use dpb_synth::contact::emg::{SurfaceEmgGenerator, SurfaceEmgParams};
use dpb_synth::contact::ppg::{PpgWaveformGenerator, PpgWaveformParams};
use dpb_synth::neural::eeg::{BandPowerConfig, EegGenerator};
use dpb_synth::traits::SyntheticGenerator;
use numpy::ndarray::Array2;

use crate::types::{PyGroundTruth, PyTimeSeries};
use numpy::PyArray2;
use pyo3::PyClassInitializer;
use pyo3::prelude::*;
use pyo3::types::PyDict;
use std::collections::HashMap;

/// Base synthetic data generator
#[pyclass(name = "SyntheticGenerator", subclass)]
pub struct PySyntheticGenerator {
    name: String,
    config: HashMap<String, f64>,
}

#[pymethods]
impl PySyntheticGenerator {
    #[new]
    #[pyo3(signature = (name="base", config=None))]
    fn new(name: &str, config: Option<HashMap<String, f64>>) -> Self {
        Self {
            name: name.to_string(),
            config: config.unwrap_or_default(),
        }
    }

    /// Generate synthetic signal data
    ///
    /// Args:
    ///     duration (float): Duration in seconds
    ///     sample_rate (float): Sampling rate in Hz
    ///     seed (int): Random seed for reproducibility
    ///
    /// Returns:
    ///     tuple: (TimeSeries, GroundTruth)
    fn generate(
        &self,
        duration: f64,
        sample_rate: f64,
        _seed: Option<u64>,
        py: Python,
    ) -> PyResult<(PyTimeSeries, PyGroundTruth)> {
        // Base implementation - override in subclasses
        let num_samples = (duration * sample_rate) as usize;
        let data = PyArray2::<f32>::zeros(py, (num_samples, 1), false);
        let signal = PyTimeSeries::new(data.into(), sample_rate, 0.0);
        let ground_truth = PyGroundTruth::new(None, None, None);

        Ok((signal, ground_truth))
    }

    #[getter]
    fn name(&self) -> String {
        self.name.clone()
    }

    #[getter]
    fn config(&self) -> HashMap<String, f64> {
        self.config.clone()
    }

    fn __repr__(&self) -> String {
        format!("SyntheticGenerator(name='{}')", self.name)
    }
}

/// ECG synthetic data generator
///
/// Generates realistic synthetic ECG signals.
///
/// Args:
///     heart_rate (float): Mean heart rate in BPM
///     hrv_sdnn (float): Heart rate variability (SDNN in ms)
///     noise_level (float): Additive noise level
///     artifacts (bool): Include artifacts (baseline wander, etc.)
///
/// Example:
///     >>> gen = EcgGenerator(heart_rate=70, hrv_sdnn=50)
///     >>> signal, ground_truth = gen.generate(duration=60.0, sample_rate=250.0)
#[pyclass(name = "EcgGenerator", extends=PySyntheticGenerator)]
// Recorded from the Python-side constructor. The wrapper does not consume
// these yet, but dropping them would silently discard what a caller
// passed through the binding.
#[allow(dead_code)]
pub struct PyEcgGenerator {
    heart_rate: f64,
    hrv_sdnn: f64,
    noise_level: f64,
    artifacts: bool,
}

#[pymethods]
impl PyEcgGenerator {
    #[new]
    #[pyo3(signature = (heart_rate=70.0, hrv_sdnn=50.0, noise_level=0.05, artifacts=false))]
    fn new(
        heart_rate: f64,
        hrv_sdnn: f64,
        noise_level: f64,
        artifacts: bool,
    ) -> PyClassInitializer<Self> {
        let mut config = HashMap::new();
        config.insert("heart_rate".to_string(), heart_rate);
        config.insert("hrv_sdnn".to_string(), hrv_sdnn);
        config.insert("noise_level".to_string(), noise_level);

        PyClassInitializer::from(PySyntheticGenerator {
            name: "ECG".to_string(),
            config,
        })
        .add_subclass(Self {
            heart_rate,
            hrv_sdnn,
            noise_level,
            artifacts,
        })
    }

    #[pyo3(signature = (duration, sample_rate, seed=None))]
    fn generate(
        &self,
        duration: f64,
        sample_rate: f64,
        seed: Option<u64>,
        py: Python,
    ) -> PyResult<(PyTimeSeries, PyGroundTruth)> {
        // Generated by `dpb_synth::EcgMorphologyGenerator` rather than returned
        // as zeros. The R-peak times below are the generator's own event-level
        // ground truth, one per cardiac cycle.
        let params = EcgMorphologyParams {
            duration,
            sampling_rate: sample_rate,
            heart_rate: self.heart_rate,
            ..EcgMorphologyGenerator::default_params()
        };

        let generated = EcgMorphologyGenerator
            .generate(&params, seed.unwrap_or(0))
            .map_err(|e| {
                pyo3::exceptions::PyValueError::new_err(format!("ECG generation failed: {e}"))
            })?;

        let samples: Vec<f32> = generated.signal.iter().map(|&v| v as f32).collect();
        let num_samples = samples.len();
        let array = Array2::from_shape_vec((num_samples, 1), samples)
            .map_err(|e| pyo3::exceptions::PyValueError::new_err(format!("signal shape: {e}")))?;
        let data = PyArray2::from_owned_array(py, array);
        let signal = PyTimeSeries::new(data.into(), sample_rate, 0.0);

        let timestamps: Vec<f64> = generated
            .ground_truth
            .events
            .iter()
            .map(|e| e.time)
            .collect();

        let mut ground_truth = PyGroundTruth::new(None, Some(timestamps), None);
        ground_truth.add_label("modality".to_string(), "ecg".to_string());
        ground_truth.add_label("heart_rate".to_string(), self.heart_rate.to_string());
        ground_truth.add_label("events".to_string(), "R_peak".to_string());

        Ok((signal, ground_truth))
    }

    #[getter]
    fn heart_rate(&self) -> f64 {
        self.heart_rate
    }

    #[setter]
    fn set_heart_rate(&mut self, value: f64) {
        self.heart_rate = value;
    }
}

/// PPG synthetic data generator
///
/// Generates realistic synthetic PPG (photoplethysmography) signals.
///
/// Args:
///     heart_rate (float): Mean heart rate in BPM
///     hrv_sdnn (float): Heart rate variability
///     noise_level (float): Additive noise level
///     dc_offset (float): DC component offset
///
/// Example:
///     >>> gen = PpgGenerator(heart_rate=75, hrv_sdnn=40)
///     >>> signal, ground_truth = gen.generate(duration=30.0, sample_rate=100.0)
#[pyclass(name = "PpgGenerator", extends=PySyntheticGenerator)]
// Recorded from the Python-side constructor. The wrapper does not consume
// these yet, but dropping them would silently discard what a caller
// passed through the binding.
#[allow(dead_code)]
pub struct PyPpgGenerator {
    heart_rate: f64,
    hrv_sdnn: f64,
    noise_level: f64,
    dc_offset: f64,
}

#[pymethods]
impl PyPpgGenerator {
    #[new]
    #[pyo3(signature = (heart_rate=75.0, hrv_sdnn=40.0, noise_level=0.03, dc_offset=0.5))]
    fn new(
        heart_rate: f64,
        hrv_sdnn: f64,
        noise_level: f64,
        dc_offset: f64,
    ) -> PyClassInitializer<Self> {
        let mut config = HashMap::new();
        config.insert("heart_rate".to_string(), heart_rate);
        config.insert("hrv_sdnn".to_string(), hrv_sdnn);
        config.insert("noise_level".to_string(), noise_level);
        config.insert("dc_offset".to_string(), dc_offset);

        PyClassInitializer::from(PySyntheticGenerator {
            name: "PPG".to_string(),
            config,
        })
        .add_subclass(Self {
            heart_rate,
            hrv_sdnn,
            noise_level,
            dc_offset,
        })
    }

    #[pyo3(signature = (duration, sample_rate, seed=None))]
    fn generate(
        &self,
        duration: f64,
        sample_rate: f64,
        seed: Option<u64>,
        py: Python,
    ) -> PyResult<(PyTimeSeries, PyGroundTruth)> {
        // Generated by `dpb_synth::PpgWaveformGenerator`.
        let params = PpgWaveformParams {
            duration,
            sampling_rate: sample_rate,
            heart_rate: self.heart_rate,
            ..PpgWaveformGenerator::default_params()
        };
        let generated = PpgWaveformGenerator
            .generate(&params, seed.unwrap_or(0))
            .map_err(|e| {
                pyo3::exceptions::PyValueError::new_err(format!("PPG generation failed: {e}"))
            })?;

        let samples: Vec<f32> = generated.signal.iter().map(|&v| v as f32).collect();
        let num_samples = samples.len();
        let array = Array2::from_shape_vec((num_samples, 1), samples)
            .map_err(|e| pyo3::exceptions::PyValueError::new_err(format!("signal shape: {e}")))?;
        let data = PyArray2::from_owned_array(py, array);
        let signal = PyTimeSeries::new(data.into(), sample_rate, 0.0);

        let mut ground_truth = PyGroundTruth::new(None, None, None);
        ground_truth.add_label("modality".to_string(), "ppg".to_string());

        Ok((signal, ground_truth))
    }
}

/// Accelerometer synthetic data generator
///
/// Generates realistic synthetic accelerometer data (3-axis).
///
/// Args:
///     activity (str): Activity type ('rest', 'walk', 'run', 'gesture')
///     noise_level (float): Sensor noise level
///     sampling_jitter (float): Timing jitter
///
/// Example:
///     >>> gen = AccelerometerGenerator(activity='walk')
///     >>> signal, ground_truth = gen.generate(duration=10.0, sample_rate=50.0)
#[pyclass(name = "AccelerometerGenerator", extends=PySyntheticGenerator)]
// Recorded from the Python-side constructor. The wrapper does not consume
// these yet, but dropping them would silently discard what a caller
// passed through the binding.
#[allow(dead_code)]
pub struct PyAccelerometerGenerator {
    activity: String,
    noise_level: f64,
    sampling_jitter: f64,
}

#[pymethods]
impl PyAccelerometerGenerator {
    #[new]
    #[pyo3(signature = (activity="rest", noise_level=0.02, sampling_jitter=0.001))]
    fn new(activity: &str, noise_level: f64, sampling_jitter: f64) -> PyClassInitializer<Self> {
        let mut config = HashMap::new();
        config.insert("noise_level".to_string(), noise_level);
        config.insert("sampling_jitter".to_string(), sampling_jitter);

        PyClassInitializer::from(PySyntheticGenerator {
            name: "Accelerometer".to_string(),
            config,
        })
        .add_subclass(Self {
            activity: activity.to_string(),
            noise_level,
            sampling_jitter,
        })
    }

    /// Generate three-axis accelerometer data.
    ///
    /// Gravity on the vertical axis, an activity-dependent periodic component,
    /// and sensor noise. The previous body returned a zero array and used none
    /// of `activity`, `noise_level` or `sampling_jitter`, while the class
    /// documented "realistic synthetic" data with an activity knob.
    ///
    /// There is no accelerometer generator in `dpb_synth` to delegate to, so
    /// this is deliberately a simple kinematic model rather than a pretence at
    /// physiological realism: gravity plus a band-limited oscillation at the
    /// activity's cadence.
    #[pyo3(signature = (duration, sample_rate, seed=None))]
    fn generate(
        &self,
        duration: f64,
        sample_rate: f64,
        seed: Option<u64>,
        py: Python,
    ) -> PyResult<(PyTimeSeries, PyGroundTruth)> {
        const GRAVITY: f64 = 9.81;

        let num_samples = (duration * sample_rate) as usize;
        if num_samples == 0 {
            return Err(pyo3::exceptions::PyValueError::new_err(
                "duration * sample_rate rounds to zero samples",
            ));
        }

        // Cadence in Hz and motion amplitude in m/s^2 per activity.
        let (cadence, amplitude) = match self.activity.to_ascii_lowercase().as_str() {
            "rest" | "resting" | "still" => (0.0, 0.0),
            "walk" | "walking" => (1.9, 2.5),
            "run" | "running" => (2.8, 8.0),
            "tremor" => (5.0, 1.2),
            other => {
                return Err(pyo3::exceptions::PyValueError::new_err(format!(
                    "unknown activity '{other}'; expected rest, walking, running or tremor"
                )));
            }
        };

        // Deterministic given the seed, so a caller can reproduce a dataset.
        let mut state = seed
            .unwrap_or(0)
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1);
        let mut noise = move || {
            // xorshift, then map to roughly [-1, 1].
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            ((state >> 11) as f64 / (1u64 << 53) as f64) * 2.0 - 1.0
        };

        let mut flat = Vec::with_capacity(num_samples * 3);
        for i in 0..num_samples {
            // Jitter perturbs the sampling instant, which is what a real
            // device's clock does.
            let t = i as f64 / sample_rate + self.sampling_jitter * noise();
            let phase = std::f64::consts::TAU * cadence * t;

            // x and y carry the horizontal sway, z carries gravity plus the
            // vertical component of the gait cycle.
            let x = amplitude * 0.4 * phase.sin() + self.noise_level * noise();
            let y = amplitude * 0.3 * (phase + 1.0).sin() + self.noise_level * noise();
            let z = GRAVITY + amplitude * phase.cos() + self.noise_level * noise();

            flat.push(x as f32);
            flat.push(y as f32);
            flat.push(z as f32);
        }

        let array = Array2::from_shape_vec((num_samples, 3), flat).map_err(|e| {
            pyo3::exceptions::PyValueError::new_err(format!("accelerometer shape: {e}"))
        })?;
        let data = PyArray2::from_owned_array(py, array);
        let signal = PyTimeSeries::new(data.into(), sample_rate, 0.0);

        let mut ground_truth = PyGroundTruth::new(None, None, None);
        ground_truth.add_label("modality".to_string(), "accelerometer".to_string());
        ground_truth.add_label("activity".to_string(), self.activity.clone());
        ground_truth.add_label("cadence_hz".to_string(), cadence.to_string());

        Ok((signal, ground_truth))
    }
}

/// EMG synthetic data generator
///
/// Generates synthetic EMG (electromyography) signals.
///
/// Args:
///     muscle_activation (float): Activation level (0-1)
///     fatigue_rate (float): Muscle fatigue rate
///     noise_level (float): Sensor noise
///
/// Example:
///     >>> gen = EmgGenerator(muscle_activation=0.6, fatigue_rate=0.01)
///     >>> signal, ground_truth = gen.generate(duration=20.0, sample_rate=1000.0)
#[pyclass(name = "EmgGenerator", extends=PySyntheticGenerator)]
// Recorded from the Python-side constructor. The wrapper does not consume
// these yet, but dropping them would silently discard what a caller
// passed through the binding.
#[allow(dead_code)]
pub struct PyEmgGenerator {
    muscle_activation: f64,
    fatigue_rate: f64,
    noise_level: f64,
}

#[pymethods]
impl PyEmgGenerator {
    #[new]
    #[pyo3(signature = (muscle_activation=0.5, fatigue_rate=0.01, noise_level=0.05))]
    fn new(
        muscle_activation: f64,
        fatigue_rate: f64,
        noise_level: f64,
    ) -> PyClassInitializer<Self> {
        let mut config = HashMap::new();
        config.insert("muscle_activation".to_string(), muscle_activation);
        config.insert("fatigue_rate".to_string(), fatigue_rate);
        config.insert("noise_level".to_string(), noise_level);

        PyClassInitializer::from(PySyntheticGenerator {
            name: "EMG".to_string(),
            config,
        })
        .add_subclass(Self {
            muscle_activation,
            fatigue_rate,
            noise_level,
        })
    }

    #[pyo3(signature = (duration, sample_rate, seed=None))]
    fn generate(
        &self,
        duration: f64,
        sample_rate: f64,
        seed: Option<u64>,
        py: Python,
    ) -> PyResult<(PyTimeSeries, PyGroundTruth)> {
        // Generated by `dpb_synth::SurfaceEmgGenerator`.
        let params = SurfaceEmgParams {
            duration,
            sampling_rate: sample_rate,
            contraction_level: self.muscle_activation,
            ..SurfaceEmgGenerator::default_params()
        };
        let generated = SurfaceEmgGenerator
            .generate(&params, seed.unwrap_or(0))
            .map_err(|e| {
                pyo3::exceptions::PyValueError::new_err(format!("EMG generation failed: {e}"))
            })?;

        let samples: Vec<f32> = generated.signal.iter().map(|&v| v as f32).collect();
        let num_samples = samples.len();
        let array = Array2::from_shape_vec((num_samples, 1), samples)
            .map_err(|e| pyo3::exceptions::PyValueError::new_err(format!("signal shape: {e}")))?;
        let data = PyArray2::from_owned_array(py, array);
        let signal = PyTimeSeries::new(data.into(), sample_rate, 0.0);

        let mut ground_truth = PyGroundTruth::new(None, None, None);
        ground_truth.add_label("modality".to_string(), "emg".to_string());

        Ok((signal, ground_truth))
    }
}

/// EEG synthetic data generator
///
/// Generates synthetic EEG (electroencephalography) signals.
///
/// Args:
///     num_channels (int): Number of EEG channels
///     dominant_frequency (float): Dominant frequency band (Hz)
///     noise_level (float): Background noise level
///
/// Example:
///     >>> gen = EegGenerator(num_channels=8, dominant_frequency=10.0)
///     >>> signal, ground_truth = gen.generate(duration=60.0, sample_rate=256.0)
#[pyclass(name = "EegGenerator", extends=PySyntheticGenerator)]
// Recorded from the Python-side constructor. The wrapper does not consume
// these yet, but dropping them would silently discard what a caller
// passed through the binding.
#[allow(dead_code)]
pub struct PyEegGenerator {
    num_channels: usize,
    dominant_frequency: f64,
    noise_level: f64,
}

#[pymethods]
impl PyEegGenerator {
    #[new]
    #[pyo3(signature = (num_channels=8, dominant_frequency=10.0, noise_level=0.1))]
    fn new(
        num_channels: usize,
        dominant_frequency: f64,
        noise_level: f64,
    ) -> PyClassInitializer<Self> {
        let mut config = HashMap::new();
        config.insert("num_channels".to_string(), num_channels as f64);
        config.insert("dominant_frequency".to_string(), dominant_frequency);
        config.insert("noise_level".to_string(), noise_level);

        PyClassInitializer::from(PySyntheticGenerator {
            name: "EEG".to_string(),
            config,
        })
        .add_subclass(Self {
            num_channels,
            dominant_frequency,
            noise_level,
        })
    }

    /// Generate multi-channel EEG.
    ///
    /// Produced by `dpb_synth::EegGenerator` rather than returned as zeros.
    /// The previous body allocated a zero array and ignored `num_channels`'
    /// siblings entirely -- `dominant_frequency` and `noise_level` were
    /// recorded at construction and never reached the signal -- while the class
    /// documented "realistic synthetic" data.
    #[pyo3(signature = (duration, sample_rate, seed=None))]
    fn generate(
        &self,
        duration: f64,
        sample_rate: f64,
        seed: Option<u64>,
        py: Python,
    ) -> PyResult<(PyTimeSeries, PyGroundTruth)> {
        let generator = EegGenerator {
            sample_rate,
            channels: self.num_channels,
            noise_level: self.noise_level,
        };

        // `dominant_frequency` selects which band carries the power, which is
        // what a caller asking for a dominant frequency means.
        let config = band_config_for(self.dominant_frequency);

        let mut channels: Vec<Vec<f64>> = Vec::with_capacity(self.num_channels);
        for _ in 0..self.num_channels {
            channels.push(generator.generate_channel(duration, &config));
        }

        let num_samples = channels.first().map_or(0, Vec::len);
        let mut flat = Vec::with_capacity(num_samples * self.num_channels);
        for s in 0..num_samples {
            for ch in &channels {
                flat.push(ch[s] as f32);
            }
        }

        let array = Array2::from_shape_vec((num_samples, self.num_channels), flat)
            .map_err(|e| pyo3::exceptions::PyValueError::new_err(format!("eeg shape: {e}")))?;
        let data = PyArray2::from_owned_array(py, array);
        let signal = PyTimeSeries::new(data.into(), sample_rate, 0.0);

        let mut ground_truth = PyGroundTruth::new(None, None, None);
        ground_truth.add_label("modality".to_string(), "eeg".to_string());
        ground_truth.add_label(
            "dominant_frequency".to_string(),
            self.dominant_frequency.to_string(),
        );
        let _ = seed;

        Ok((signal, ground_truth))
    }
}

/// Band powers with the band containing `dominant_hz` carrying most of them.
///
/// A caller who asks for a dominant frequency is asking which rhythm should
/// stand out; the underlying generator takes relative band powers, so the
/// request is translated into them here.
fn band_config_for(dominant_hz: f64) -> BandPowerConfig {
    let mut c = BandPowerConfig {
        delta: 0.1,
        theta: 0.1,
        alpha: 0.1,
        beta: 0.1,
        gamma: 0.1,
    };
    let dominant = 0.6;
    let alpha_is_dominant = (8.0..13.0).contains(&dominant_hz);
    match dominant_hz {
        f if f < 4.0 => c.delta = dominant,
        f if f < 8.0 => c.theta = dominant,
        f if f < 13.0 => c.alpha = dominant,
        f if f < 30.0 => c.beta = dominant,
        _ => c.gamma = dominant,
    }

    // The generator models alpha as a pure 10 Hz tone while every other band is
    // broadband noise. All of a tone's energy lands in one spectral bin, so a
    // background alpha at any audible level takes the spectral peak no matter
    // how much power the requested band carries -- the dominant frequency would
    // be 10 Hz whatever was asked for. Alpha is therefore left out unless it is
    // the band being asked for. (The generator drops any band whose normalised
    // power is below 0.01.)
    if !alpha_is_dominant {
        c.alpha = 0.0;
    }
    c
}

/// Batch generator for creating multiple synthetic samples
///
/// Args:
///     generator: Base generator to use
///     batch_size (int): Number of samples per batch
///
/// Example:
///     >>> base_gen = EcgGenerator(heart_rate=70)
///     >>> batch_gen = BatchGenerator(base_gen, batch_size=32)
///     >>> signals, ground_truths = batch_gen.generate_batch(duration=10.0)
#[pyclass(name = "BatchGenerator")]
pub struct PyBatchGenerator {
    /// The generator each sample is drawn from.
    ///
    /// This used to be accepted and dropped, so the batch generator had nothing
    /// to delegate to and returned buffers of zeros.
    generator: Py<PyAny>,
    batch_size: usize,
}

#[pymethods]
impl PyBatchGenerator {
    #[new]
    fn new(generator: Py<PyAny>, batch_size: usize) -> Self {
        Self {
            generator,
            batch_size,
        }
    }

    /// Generate a batch of synthetic samples
    fn generate_batch(
        &self,
        duration: f64,
        sample_rate: f64,
        py: Python,
        // The signals and ground truths come back as the generator's own
        // objects rather than being re-wrapped, so nothing needs cloning.
    ) -> PyResult<(Vec<Py<PyAny>>, Vec<Py<PyAny>>)> {
        let mut signals = Vec::new();
        let mut ground_truths = Vec::new();

        // Delegate to the wrapped generator, one call per sample with a
        // distinct seed so the batch is varied rather than repeated.
        for i in 0..self.batch_size {
            let result =
                self.generator
                    .call_method1(py, "generate", (duration, sample_rate, i as u64))?;
            let bound = result.bind(py);
            let signal = bound.get_item(0)?.unbind();
            let ground_truth = bound.get_item(1)?.unbind();

            signals.push(signal);
            ground_truths.push(ground_truth);
        }

        Ok((signals, ground_truths))
    }
}

/// Factory function to create generators by name
///
/// Args:
///     name (str): Generator name ('ecg', 'ppg', 'accelerometer', etc.)
///     config (dict): Configuration dictionary
///
/// Returns:
///     SyntheticGenerator: Configured generator instance
///
/// Example:
///     >>> gen = create_generator('ecg', {'heart_rate': 70, 'hrv_sdnn': 50})
#[pyfunction]
fn create_generator(name: &str, config: Option<&Bound<'_, PyDict>>) -> PyResult<Py<PyAny>> {
    Python::attach(|py| {
        let generator: Py<PyAny> = match name {
            "ecg" => {
                let heart_rate = config
                    .and_then(|c| c.get_item("heart_rate").ok().flatten())
                    .map(|v| v.extract::<f64>().unwrap_or(70.0))
                    .unwrap_or(70.0);

                Py::new(py, PyEcgGenerator::new(heart_rate, 50.0, 0.05, false))?.into_any()
            }
            "ppg" => Py::new(py, PyPpgGenerator::new(75.0, 40.0, 0.03, 0.5))?.into_any(),
            "accelerometer" => {
                Py::new(py, PyAccelerometerGenerator::new("rest", 0.02, 0.001))?.into_any()
            }
            "emg" => Py::new(py, PyEmgGenerator::new(0.5, 0.01, 0.05))?.into_any(),
            "eeg" => Py::new(py, PyEegGenerator::new(8, 10.0, 0.1))?.into_any(),
            _ => {
                return Err(pyo3::exceptions::PyValueError::new_err(format!(
                    "Unknown generator: {}",
                    name
                )));
            }
        };

        Ok(generator)
    })
}

/// Register synth module
pub fn register_module(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<PySyntheticGenerator>()?;
    m.add_class::<PyEcgGenerator>()?;
    m.add_class::<PyPpgGenerator>()?;
    m.add_class::<PyAccelerometerGenerator>()?;
    m.add_class::<PyEmgGenerator>()?;
    m.add_class::<PyEegGenerator>()?;
    m.add_class::<PyBatchGenerator>()?;
    m.add_function(wrap_pyfunction!(create_generator, m)?)?;
    Ok(())
}
