//! Python wrappers for core DPB types

use numpy::{PyArray1, PyArray2, PyArrayMethods};
use pyo3::prelude::*;
use pyo3::types::PyDict;
use std::collections::HashMap;

/// A single spike event
///
/// Represents a discrete event generated by an encoder at a specific time.
///
/// Attributes:
///     timestamp (float): Event time in seconds
///     channel (int): Channel/neuron index
///     polarity (int): Event polarity (-1, 0, +1)
///     magnitude (float): Event magnitude/strength
#[pyclass(name = "SpikeEvent")]
#[derive(Clone, Debug)]
pub struct PySpikeEvent {
    #[pyo3(get, set)]
    pub timestamp: f64,
    #[pyo3(get, set)]
    pub channel: u32,
    #[pyo3(get, set)]
    pub polarity: i8,
    #[pyo3(get, set)]
    pub magnitude: f32,
}

#[pymethods]
impl PySpikeEvent {
    #[new]
    #[pyo3(signature = (timestamp, channel, polarity=1, magnitude=1.0))]
    pub fn new(timestamp: f64, channel: u32, polarity: i8, magnitude: f32) -> Self {
        Self {
            timestamp,
            channel,
            polarity,
            magnitude,
        }
    }

    fn __repr__(&self) -> String {
        format!(
            "SpikeEvent(t={:.6}, ch={}, pol={}, mag={:.3})",
            self.timestamp, self.channel, self.polarity, self.magnitude
        )
    }

    fn __str__(&self) -> String {
        self.__repr__()
    }

    /// Create from dictionary
    #[staticmethod]
    fn from_dict(d: &Bound<'_, PyDict>) -> PyResult<Self> {
        Ok(Self {
            timestamp: d
                .get_item("timestamp")?
                .ok_or_else(|| pyo3::exceptions::PyKeyError::new_err("Missing key: 'timestamp'"))?
                .extract()?,
            channel: d
                .get_item("channel")?
                .ok_or_else(|| pyo3::exceptions::PyKeyError::new_err("Missing key: 'channel'"))?
                .extract()?,
            polarity: d
                .get_item("polarity")?
                .map(|v| v.extract())
                .transpose()?
                .unwrap_or(1),
            magnitude: d
                .get_item("magnitude")?
                .map(|v| v.extract())
                .transpose()?
                .unwrap_or(1.0),
        })
    }

    /// Convert to dictionary
    fn to_dict(&self, py: Python) -> PyResult<PyObject> {
        let dict = PyDict::new(py);
        dict.set_item("timestamp", self.timestamp)?;
        dict.set_item("channel", self.channel)?;
        dict.set_item("polarity", self.polarity)?;
        dict.set_item("magnitude", self.magnitude)?;
        Ok(dict.into())
    }
}

/// A sequence of spike events
///
/// Represents the output of an encoder or a layer in an SNN.
///
/// Attributes:
///     events (list[SpikeEvent]): List of spike events
///     duration (float): Total duration in seconds
///     num_channels (int): Number of channels
#[pyclass(name = "SpikeTrain")]
#[derive(Clone)]
pub struct PySpikeTrain {
    #[pyo3(get)]
    pub events: Vec<PySpikeEvent>,
    #[pyo3(get, set)]
    pub duration: f64,
    #[pyo3(get, set)]
    pub num_channels: u32,
}

#[pymethods]
impl PySpikeTrain {
    #[new]
    #[pyo3(signature = (events=None, duration=0.0, num_channels=1))]
    pub fn new(events: Option<Vec<PySpikeEvent>>, duration: f64, num_channels: u32) -> Self {
        Self {
            events: events.unwrap_or_default(),
            duration,
            num_channels,
        }
    }

    /// Add a spike event
    fn add_event(&mut self, event: PySpikeEvent) {
        self.events.push(event);
    }

    /// Get number of events
    fn __len__(&self) -> usize {
        self.events.len()
    }

    /// Get event by index
    fn __getitem__(&self, idx: usize) -> PyResult<PySpikeEvent> {
        self.events
            .get(idx)
            .cloned()
            .ok_or_else(|| pyo3::exceptions::PyIndexError::new_err("Index out of range"))
    }

    fn __repr__(&self) -> String {
        format!(
            "SpikeTrain(events={}, duration={:.3}s, channels={})",
            self.events.len(),
            self.duration,
            self.num_channels
        )
    }

    /// Sort events by timestamp
    fn sort_by_time(&mut self) {
        self.events.sort_by(|a, b| {
            a.timestamp
                .partial_cmp(&b.timestamp)
                .unwrap_or(std::cmp::Ordering::Equal)
        });
    }

    /// Filter events by channel
    fn filter_by_channel(&self, channel: u32) -> Self {
        let filtered = self
            .events
            .iter()
            .filter(|e| e.channel == channel)
            .cloned()
            .collect();
        Self {
            events: filtered,
            duration: self.duration,
            num_channels: self.num_channels,
        }
    }

    /// Get spike rate (Hz)
    fn spike_rate(&self) -> f64 {
        if self.duration > 0.0 {
            self.events.len() as f64 / self.duration
        } else {
            0.0
        }
    }

    /// Get spike rate per channel (Hz)
    fn spike_rate_per_channel(&self) -> HashMap<u32, f64> {
        let mut counts: HashMap<u32, usize> = HashMap::new();
        for event in &self.events {
            *counts.entry(event.channel).or_insert(0) += 1;
        }
        counts
            .into_iter()
            .map(|(ch, count)| {
                let rate = if self.duration > 0.0 {
                    count as f64 / self.duration
                } else {
                    0.0
                };
                (ch, rate)
            })
            .collect()
    }
}

/// Time series signal data
///
/// Represents continuous signal data (e.g., ECG, PPG, accelerometer).
///
/// Attributes:
///     data (ndarray): Signal data as numpy array (samples x channels)
///     sample_rate (float): Sampling rate in Hz
///     start_time (float): Start time in seconds
#[pyclass(name = "TimeSeries")]
pub struct PyTimeSeries {
    data: Py<PyArray2<f32>>,
    #[pyo3(get, set)]
    pub sample_rate: f64,
    #[pyo3(get, set)]
    pub start_time: f64,
}

#[pymethods]
impl PyTimeSeries {
    #[new]
    #[pyo3(signature = (data, sample_rate, start_time=0.0))]
    pub fn new(data: Py<PyArray2<f32>>, sample_rate: f64, start_time: f64) -> Self {
        Self {
            data,
            sample_rate,
            start_time,
        }
    }

    /// Get the data array
    #[getter]
    fn data(&self, py: Python) -> PyObject {
        self.data.clone_ref(py).into_any().into()
    }

    /// Set the data array
    #[setter]
    fn set_data(&mut self, data: Py<PyArray2<f32>>) {
        self.data = data;
    }

    /// Get number of samples
    pub fn num_samples(&self, py: Python) -> usize {
        self.data.bind(py).readonly().as_array().shape()[0]
    }

    /// Get number of channels
    pub fn num_channels(&self, py: Python) -> usize {
        self.data.bind(py).readonly().as_array().shape()[1]
    }

    /// Get duration in seconds
    pub fn duration(&self, py: Python) -> f64 {
        self.num_samples(py) as f64 / self.sample_rate
    }

    /// Get time axis as numpy array
    fn time_axis(&self, py: Python) -> PyResult<Py<PyArray1<f64>>> {
        let n = self.num_samples(py);
        let times: Vec<f64> = (0..n)
            .map(|i| self.start_time + (i as f64 / self.sample_rate))
            .collect();
        Ok(PyArray1::from_vec(py, times).into())
    }

    fn __repr__(&self, py: Python) -> String {
        format!(
            "TimeSeries(samples={}, channels={}, rate={:.1} Hz, duration={:.3}s)",
            self.num_samples(py),
            self.num_channels(py),
            self.sample_rate,
            self.duration(py)
        )
    }

    /// Extract a single channel
    pub fn get_channel(&self, py: Python, channel: usize) -> PyResult<Py<PyArray1<f32>>> {
        let readonly = self.data.bind(py).readonly();
        let array = readonly.as_array();
        let shape = array.shape();
        if channel >= shape[1] {
            return Err(pyo3::exceptions::PyIndexError::new_err(
                "Channel index out of range",
            ));
        }

        let data: Vec<f32> = (0..shape[0])
            .map(|i| array[[i, channel]])
            .collect();

        Ok(PyArray1::from_vec_bound(py, data).into())
    }
}

/// Ground truth annotations
///
/// Represents labeled events or regions in a signal.
///
/// Attributes:
///     labels (dict): Dictionary of label types to values
///     timestamps (list[float]): Event timestamps
///     regions (list[tuple]): List of (start, end) time pairs
#[pyclass(name = "GroundTruth")]
#[derive(Clone)]
pub struct PyGroundTruth {
    #[pyo3(get, set)]
    pub labels: HashMap<String, String>,
    #[pyo3(get, set)]
    pub timestamps: Vec<f64>,
    #[pyo3(get, set)]
    pub regions: Vec<(f64, f64)>,
}

#[pymethods]
impl PyGroundTruth {
    #[new]
    #[pyo3(signature = (labels=None, timestamps=None, regions=None))]
    pub fn new(
        labels: Option<HashMap<String, String>>,
        timestamps: Option<Vec<f64>>,
        regions: Option<Vec<(f64, f64)>>,
    ) -> Self {
        Self {
            labels: labels.unwrap_or_default(),
            timestamps: timestamps.unwrap_or_default(),
            regions: regions.unwrap_or_default(),
        }
    }

    /// Add a label
    pub fn add_label(&mut self, key: String, value: String) {
        self.labels.insert(key, value);
    }

    /// Add a timestamp
    fn add_timestamp(&mut self, timestamp: f64) {
        self.timestamps.push(timestamp);
    }

    /// Add a region
    fn add_region(&mut self, start: f64, end: f64) {
        self.regions.push((start, end));
    }

    fn __repr__(&self) -> String {
        format!(
            "GroundTruth(labels={}, timestamps={}, regions={})",
            self.labels.len(),
            self.timestamps.len(),
            self.regions.len()
        )
    }

    /// Get label value
    fn get_label(&self, key: &str) -> Option<String> {
        self.labels.get(key).cloned()
    }

    /// Check if timestamp is in any region
    fn in_region(&self, timestamp: f64) -> bool {
        self.regions
            .iter()
            .any(|(start, end)| timestamp >= *start && timestamp <= *end)
    }
}

/// Context information for encoders and models
///
/// Provides contextual information like patient demographics, sensor placement, etc.
///
/// Attributes:
///     metadata (dict): Key-value metadata
#[pyclass(name = "Context")]
#[derive(Clone)]
pub struct PyContext {
    #[pyo3(get, set)]
    pub metadata: HashMap<String, String>,
}

#[pymethods]
impl PyContext {
    #[new]
    #[pyo3(signature = (metadata=None))]
    fn new(metadata: Option<HashMap<String, String>>) -> Self {
        Self {
            metadata: metadata.unwrap_or_default(),
        }
    }

    /// Set metadata value
    fn set(&mut self, key: String, value: String) {
        self.metadata.insert(key, value);
    }

    /// Get metadata value
    fn get(&self, key: &str) -> Option<String> {
        self.metadata.get(key).cloned()
    }

    /// Check if key exists
    fn has(&self, key: &str) -> bool {
        self.metadata.contains_key(key)
    }

    fn __repr__(&self) -> String {
        format!("Context(metadata={})", self.metadata.len())
    }

    /// Get all keys
    fn keys(&self) -> Vec<String> {
        self.metadata.keys().cloned().collect()
    }

    /// Get all values
    fn values(&self) -> Vec<String> {
        self.metadata.values().cloned().collect()
    }
}
