//! Training analysis and convergence detection for SNNs
//!
//! This module provides comprehensive tools for analyzing SNN training dynamics,
//! detecting convergence, and comparing different training methods.

mod convergence;
mod learning_curves;
mod gradient_analysis;
mod spike_statistics;
mod weight_analysis;
mod comparison;

pub use convergence::{
    LossPlateauDetector,
    AccuracyPlateauDetector,
    EarlyStoppingAnalyzer,
    ConvergenceRateAnalyzer,
    OscillationDetector,
    DivergenceDetector,
};

pub use learning_curves::{
    LearningCurveSmoothed,
    GeneralizationGapAnalyzer,
    OverfittingDetector,
    LearningRateAnalyzer,
    BatchSizeAnalyzer,
    EpochEfficiencyAnalyzer,
};

pub use gradient_analysis::{
    GradientNormTracker,
    GradientFlowAnalyzer,
    VanishingGradientDetector,
    ExplodingGradientDetector,
    SurrogateGradientAnalyzer,
};

pub use spike_statistics::{
    SpikeRateTracker,
    SparsityTracker,
    SilentNeuronDetector,
    SaturatedNeuronDetector,
    TemporalDynamicsAnalyzer,
};

pub use weight_analysis::{
    WeightDistributionTracker,
    WeightMagnitudeTracker,
    WeightSparsityTracker,
    WeightUpdateTracker,
};

pub use comparison::{
    MethodComparisonAnalyzer,
    HyperparameterSensitivityAnalyzer,
};

use std::collections::HashMap;
use serde::{Deserialize, Serialize};

/// Core trait for all convergence analyzers
pub trait ConvergenceAnalyzer: Send + Sync {
    /// Returns the name of this analyzer
    fn name(&self) -> &str;

    /// Updates the analyzer with new training metrics
    fn update(&mut self, epoch: usize, metrics: &TrainingMetrics);

    /// Returns whether training has converged according to this analyzer
    fn is_converged(&self) -> bool;

    /// Returns the epoch at which convergence was detected, if any
    fn convergence_epoch(&self) -> Option<usize>;

    /// Generates a detailed analysis report
    fn analysis_report(&self) -> AnalysisReport;

    /// Resets the analyzer state
    fn reset(&mut self);
}

/// Training metrics collected during training
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrainingMetrics {
    /// Current epoch number
    pub epoch: usize,

    /// Training loss
    pub train_loss: f64,

    /// Validation loss (optional)
    pub val_loss: Option<f64>,

    /// Training accuracy
    pub train_accuracy: f64,

    /// Validation accuracy (optional)
    pub val_accuracy: Option<f64>,

    /// Current learning rate
    pub learning_rate: f64,

    /// Gradient norm
    pub gradient_norm: f64,

    /// Average spike rate across network
    pub spike_rate: f64,

    /// Average weight norm
    pub weight_norm: f64,

    /// Additional custom metrics
    pub custom_metrics: HashMap<String, f64>,
}

impl TrainingMetrics {
    /// Creates a new TrainingMetrics instance
    pub fn new(epoch: usize, train_loss: f64, train_accuracy: f64) -> Self {
        Self {
            epoch,
            train_loss,
            val_loss: None,
            train_accuracy,
            val_accuracy: None,
            learning_rate: 0.001,
            gradient_norm: 0.0,
            spike_rate: 0.0,
            weight_norm: 0.0,
            custom_metrics: HashMap::new(),
        }
    }

    /// Builder method to set validation loss
    pub fn with_val_loss(mut self, val_loss: f64) -> Self {
        self.val_loss = Some(val_loss);
        self
    }

    /// Builder method to set validation accuracy
    pub fn with_val_accuracy(mut self, val_accuracy: f64) -> Self {
        self.val_accuracy = Some(val_accuracy);
        self
    }

    /// Builder method to set learning rate
    pub fn with_learning_rate(mut self, learning_rate: f64) -> Self {
        self.learning_rate = learning_rate;
        self
    }

    /// Builder method to set gradient norm
    pub fn with_gradient_norm(mut self, gradient_norm: f64) -> Self {
        self.gradient_norm = gradient_norm;
        self
    }

    /// Builder method to set spike rate
    pub fn with_spike_rate(mut self, spike_rate: f64) -> Self {
        self.spike_rate = spike_rate;
        self
    }

    /// Builder method to set weight norm
    pub fn with_weight_norm(mut self, weight_norm: f64) -> Self {
        self.weight_norm = weight_norm;
        self
    }
}

/// Analysis report generated by an analyzer
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnalysisReport {
    /// Name of the analyzer
    pub analyzer_name: String,

    /// Whether convergence has been detected
    pub converged: bool,

    /// Epoch at which convergence was detected
    pub convergence_epoch: Option<usize>,

    /// Analysis metrics
    pub metrics: HashMap<String, f64>,

    /// Recommendations for improving training
    pub recommendations: Vec<String>,

    /// Additional analysis details
    pub details: HashMap<String, String>,
}

impl AnalysisReport {
    /// Creates a new empty analysis report
    pub fn new(analyzer_name: String) -> Self {
        Self {
            analyzer_name,
            converged: false,
            convergence_epoch: None,
            metrics: HashMap::new(),
            recommendations: Vec::new(),
            details: HashMap::new(),
        }
    }

    /// Adds a metric to the report
    pub fn add_metric(&mut self, key: impl Into<String>, value: f64) {
        self.metrics.insert(key.into(), value);
    }

    /// Adds a recommendation to the report
    pub fn add_recommendation(&mut self, recommendation: impl Into<String>) {
        self.recommendations.push(recommendation.into());
    }

    /// Adds a detail to the report
    pub fn add_detail(&mut self, key: impl Into<String>, value: impl Into<String>) {
        self.details.insert(key.into(), value.into());
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_training_metrics_builder() {
        let metrics = TrainingMetrics::new(1, 0.5, 0.9)
            .with_val_loss(0.6)
            .with_val_accuracy(0.85)
            .with_learning_rate(0.001)
            .with_gradient_norm(0.1)
            .with_spike_rate(0.05)
            .with_weight_norm(1.5);

        assert_eq!(metrics.epoch, 1);
        assert_eq!(metrics.train_loss, 0.5);
        assert_eq!(metrics.val_loss, Some(0.6));
        assert_eq!(metrics.val_accuracy, Some(0.85));
        assert_eq!(metrics.learning_rate, 0.001);
    }

    #[test]
    fn test_analysis_report_builder() {
        let mut report = AnalysisReport::new("TestAnalyzer".to_string());
        report.add_metric("test_metric", 1.5);
        report.add_recommendation("Try lower learning rate");
        report.add_detail("note", "Test detail");

        assert_eq!(report.analyzer_name, "TestAnalyzer");
        assert_eq!(report.metrics.get("test_metric"), Some(&1.5));
        assert_eq!(report.recommendations.len(), 1);
        assert_eq!(report.details.get("note"), Some(&"Test detail".to_string()));
    }
}
