[package]
name = "dpb-norms"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Normative databases for Delta-Predictive Biosensing assessments"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
