[package]
name = "dpb-neurons"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Neuron models for spiking neural networks"

[dependencies]
ndarray.workspace = true
bytemuck.workspace = true
serde.workspace = true
rand.workspace = true
rand_distr.workspace = true

[dev-dependencies]
approx.workspace = true
criterion.workspace = true
