[package]
name = "dpb-encoders"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Event-based encoders for DPB Framework"

[dependencies]
dpb-core.workspace = true
serde.workspace = true

[dev-dependencies]
approx.workspace = true
criterion.workspace = true
